Order management homework
sashass635/tl_practice_2024 pull request #1
Opened 2024-07-04 11:44 UTC by sashass635

2024-07-07 11:25 UTC, pklgn commented on OrderManager/OrderManager/editorconfig
Этот `.editorconfig` лишний. Насколько помню, на лекции было рекомендовано расположение внутри директории с .sln файлом. Поэтому второй `.editorconfig` файл можно оставить.

2024-07-07 11:27 UTC, pklgn commented on OrderManager/.gitignore
Я бы закинул `.gitignore` в корень репозитория. Или есть какое-то требование по размещению этого файла в директории с определенной домашкой?

2024-07-07 11:27 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static string orderDetails(string message)
Название методов с большой буквы.

2024-07-07 11:27 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static int productsAmount(string message)
Название методов с большой буквы.

2024-07-07 11:28 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static void dataRequest(out string product, out int count, out string name, out string address)
Название методов с большой буквы.

2024-07-07 11:28 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static bool orderСonfirmation(string product, int count, string name, string address)
Название методов с большой буквы.

2024-07-07 11:28 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static void successfulMessage(string product, int count, string name, string address)
Название методов с большой буквы.

2024-07-07 11:30 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static string orderDetails(string message)
Название методов должно содержать глагол, это некоторое действие. Например, в данном случае, ты читаешь из консоли детали заказа, поэтому метод можно назвать `ReadOrderDetails`.

2024-07-07 11:31 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static string orderDetails(string message)
Методы разделяются пустой строкой.

2024-07-07 11:31 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static int productsAmount(string message)
Название методов должно содержать глагол, это некоторое действие.

2024-07-07 11:31 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static void dataRequest(out string product, out int count, out string name, out string address)
Название методов должно содержать глагол, это некоторое действие.

2024-07-07 11:31 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static bool orderСonfirmation(string product, int count, string name, string address)
Название методов должно содержать глагол, это некоторое действие.

2024-07-07 11:31 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static void successfulMessage(string product, int count, string name, string address)
Название методов должно содержать глагол, это некоторое действие.

2024-07-07 11:43 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static void dataRequest(out string product, out int count, out string name, out string address)
Чтобы возвращать несколько значений, лучше использовать некоторый объект, тогда вместо `void` будет возвращаемый тип, `out` обычно используют в других ситуациях (например, в [TryParse](https://learn.microsoft.com/ru-ru/dotnet/api/system.int32.tryparse?view=net-8.0)) . В данном случае таким типом может быть объект `Order`, который будет содержать поля с названием продукта, количеством, именем пользователя и адресом. Но объекты, как я понимаю, на лекциях c этой домашкой рассмотрены еще не были, поэтому предлагаю написать несколько функций, которые будут возвращать `string`: например `ReadProductName()`, `ReadProductCount()` и т.д. Либо написать одну функцию (потому что реализация у таких `Read<что-то_там>` по сути идентична), в которую будет передан текст подсказки для пользователя и которая будет считывать и возвращать введенную пользователем строку.

2024-07-07 11:56 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +        static void dataRequest(out string product, out int count, out string name, out string address)
У тебя уже есть такие функции для чтения инфы от пользователя, предлагаю пока избавиться от `dataRequest` и вместо ее вызова, использовать сразу текущий вариант реализации. 
```
            product = ReadUserInput("Название товара: ");
            count = ReadUserInput("Количество товара: ");
            name = ReadUserInput("Имя пользователя: ");
            address = ReadUserInput("Адрес доставки: ");
```
Методы могут иметь одинаковое название, но разную сигнатуру, это так называемая [перегрузка методов](https://metanit.com/sharp/tutorial/3.5.php)

2024-07-07 12:15 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +using System.Xml.Linq;
Лишние `using`и.

2024-07-07 12:38 UTC, pklgn commented on OrderManager/editorconfig
Название должно быть с точкой в начале: `.editorconfig`. Поправь название и отформатируй код через `ctrl + e, ctrl + d`, как [тут](https://stackoverflow.com/questions/4942113/is-there-a-format-code-shortcut-for-visual-studio) указано.

2024-07-07 12:39 UTC, pklgn commented on OrderManager/editorconfig
Должны появиться отступы между методами и пробелы внутри скобок около параметров.

2024-07-07 12:41 UTC, pklgn requested changes
Нужны доработки.

2024-07-07 13:57 UTC, sashass635 commented
Программу доработала согласно твоим замечаниям.

2024-07-16 22:05 UTC, pklgn commented on OrderManager/OrderManager/Program.cs
> +            return ( confirmation == "да" );
Забыл написать в прошлый раз, такие строковые литералы вроде "да" и другие (числа, например) лучше выносить в константы и давать им понятное название. В коде не должно быть магических констант. Тут могу предложить почитать Чистый код Роберта Мартина. Там много таких моментов написано, которые помогут сделать код понятнее и устойчивее к рефакторингу, например.

2024-07-16 22:06 UTC, pklgn commented
Все круто, только не забывай в таблице с лабами отмечать исправленные лабы с оранжевого на серый цвет (после того, как поправишь замечания).

2024-07-16 22:07 UTC, pklgn approved these changes
LGTM!

2024-07-17 17:49 UTC, merged