Dictionary homework
sashass635/tl_practice_2024 pull request #3
Opened 2024-07-07 15:32 UTC by sashass635

2024-07-16 22:09 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +        const string filePath = "dictionary.txt";
Константы вроде в `CamelCase` именуются. То есть будет `FilePath`. Только точное ли это название? Может стоит назвать `DictionaryFilePath`?

2024-07-16 22:12 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                Console.WriteLine( "Выберите команду или нажмите '0', чтобы их посмотреть: " );
Лучше выводить набор команд при первоначальном запуске утилиты без действий пользователя. То есть запустил программу и сразу увидел, что программа может делать. Ну это так, уже больше к пользовательскому опыту вопрос, просто решил отметить)

2024-07-16 22:14 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                if ( Console.ReadLine().ToLower() == "да" )
Магическая константа "да". Нужно явно вынести в константу.

2024-07-16 22:14 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                using ( var writer = new StreamWriter( filePath ) )
`var` не используем.

2024-07-16 22:14 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                    foreach ( var word in dictionary )
`var` не используем.

2024-07-16 22:26 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                    Console.WriteLine( "Неверная команда. Повторите ввод.\n" );
Дублируем как будто бы обработку неверного парсинга и отсутствующей команды. Одно и то же сообщение выводится. Уже сейчас, если я захочу поправить текст сообщения, то придется делать это в двух местах в коде и есть вероятность забыть внести изменения в `default` ветку `switch`'а, например. Предлагаю подумать, как можно избежать дублирования. 
Или здесь не дублирование, а просто совпадение? Одна и та же ли это ситуация, которая предполагает одинаковую обработку или разные, которые просто сейчас совпали?

2024-07-16 22:29 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +            if ( !dictionary.ContainsKey( word ) && !dictionary.ContainsValue( word ) )
Почему именно такая проверка? Почему не `( !dictionary.ContainsKey( word ) && !dictionary.ContainsKey( translation ) )`, например?

2024-07-16 22:30 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +            if ( !dictionary.ContainsKey( word ) && !dictionary.ContainsValue( word ) )
А если перевод был введен неверный, то я не смогу поменять значение перевода?

2024-07-16 22:30 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                foreach ( var word in dictionary )
`var` не используем.

2024-07-16 22:31 UTC, pklgn commented
Аккуратный код, предлагаю чуть поработать над логикой работы программы.

2024-07-16 22:31 UTC, pklgn requested changes
Нужны доработки.

2024-07-17 19:50 UTC, sashass635 commented on Dictionary/Dictionary/Program.cs
> +                    Console.WriteLine( "Неверная команда. Повторите ввод.\n" );
Ситуации разные, просто выводится одно и то же сообщение. Решила сообщение при обработке отсутствующей команды вынести в отдельную процедуру.

2024-07-17 19:51 UTC, sashass635 commented on Dictionary/Dictionary/Program.cs
> +            if ( !dictionary.ContainsKey( word ) && !dictionary.ContainsValue( word ) )
> Почему именно такая проверка? Почему не `( !dictionary.ContainsKey( word ) && !dictionary.ContainsKey( translation ) )`, например?

Поняла, сделала, как ты предложил. Я просто думала, что поскольку у нас слово добавляется сразу в обе стороны  (русское слово как ключ и английское слово как значение, и наоборот), то такая проверка имеет место.

2024-07-17 19:52 UTC, sashass635 commented on Dictionary/Dictionary/Program.cs
> +            if ( !dictionary.ContainsKey( word ) && !dictionary.ContainsValue( word ) )
> А если перевод был введен неверный, то я не смогу поменять значение перевода?

В ТЗ ничего не говориться о том, что пользователь может менять значение перевода, но реализовала.

2024-07-17 19:52 UTC, sashass635 commented
Программу доработала согласно замечаниям.

2024-07-20 19:43 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +            int choice;
В копилку про чистый код: переменную нужно стараться объявлять как можно ближе к месту, где она используется. То есть в данном случае `choice` должна быть перед `do while` блоком. Использование этого правила позволяет чуть быстрее читать и понимать код. В рамках данной работы можно не исправлять, но на будущее стоит иметь в виду)

2024-07-20 20:26 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +                Console.WriteLine( "Слово уже существует. Хотите заменить перевод? (да/нет)" );
Вот тут интересно получается: если у нас была старая пара ключ-значение ранее, но мы решили ее обновить, то для старого перевода слова мы сохраним старый перевод. Конечно можно сказать, что это не баг, а фича, но как будто это неочевидное поведение программы. Приведу пример:
мы ввели пару `машина:cat`
сохранили в словарь следующие переводы: 
```
машина->cat
cat->машина
```
потом увидели опечатку (ведь машина это car) 
и решили ввести новый перевод
вводим пару `машина:car`
и получается, что мы обновим пару `машина->car`
но вот обратный перевод останется: `cat->машина`
то есть у нас будет
```
машина->car
car->машина
cat->машина
```
и тут как будто бы уже неочевидная ситуация при извлечении данных из словаря.
Тут два варианта: удалять старое при обновлении
Либо упростить и убрать сохранение перевода в обе стороны, и оставить только пару слово-перевод.

2024-07-20 20:27 UTC, pklgn commented on Dictionary/Dictionary/Program.cs
> +            if ( !dictionary.ContainsKey( word ) && !dictionary.ContainsValue( word ) )
Круто!

2024-07-20 20:32 UTC, pklgn commented
Поскольку редактирование не упоминается в ТЗ, то его можно не дорабатывать. В рамках изначального задания реализовано все, поэтому аппрув, но если будет возможность и интерес, можно потом вернуться к редактированию и доработать его.

2024-07-20 20:35 UTC, pklgn commented on Dictionary/Dictionary.sln
> +<<<<<<< Updated upstream
Вот тут непонятная ситуация с изменениями из стеша. Таких артефактов гита вроде `<<<<<<< Updated upstream` в `.sln` файле быть не должно. Нужно убрать лишний проект. Сейчас два одинаковых проекта в солюшене находятся.

2024-07-20 21:56 UTC, sashass635 commented on Dictionary/Dictionary/Program.cs
> +                Console.WriteLine( "Слово уже существует. Хотите заменить перевод? (да/нет)" );
При обновлении перевода решила удалять старые значения.

2024-07-21 12:33 UTC, pklgn approved these changes
LGTM!

2024-07-22 18:33 UTC, merged