SQL homework
sashass635/tl_practice_2024 pull request #5
Opened 2024-07-15 16:50 UTC by sashass635

2024-07-20 22:54 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +    CONSTRAINT FK_Bookings_room_id
Отступ.

2024-07-20 22:56 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +	CONSTRAINT PK_Rooms_room_id PRIMARY KEY (room_id)
Лучше называть `PK_rooms_room_id`

2024-07-20 22:56 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +
Лишняя строка.

2024-07-20 22:56 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +
Лишняя строка.

2024-07-20 22:57 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +	facility_name NVARCHAR(100) NOT NULL,
Может просто `name` назвать?

2024-07-20 23:01 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +VALUES	('100', 'Standard', 75.00, 2),
Перенеси тут и в других `INSERT` первое значение на новую строку, чтобы читалось лучше и все значения были с одним отступом.

2024-07-20 23:03 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +WHERE  availability > 0 AND room_id NOT IN (
Или `<>`?

2024-07-20 23:05 UTC, pklgn requested changes
Нужны доработки.

2024-07-21 11:40 UTC, sashass635 commented on SQL/SQL_HotelManagement.sql
> +	facility_name NVARCHAR(100) NOT NULL,
В ТЗ указано, что название должно быть facility_name.

2024-07-21 11:42 UTC, sashass635 commented on SQL/SQL_HotelManagement.sql
> +WHERE  availability > 0 AND room_id NOT IN (
Поскольку нам нужно найти все номера, которые не забронированы на определенную дату, то проверки ```availability <> 0``` и  ```availability > 0```, мне кажется, подойдут. Нам важно знать, что количество доступных номеров имеет любое значение отличное от нуля.

2024-07-21 12:50 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +WHERE  availability > 0 AND room_id NOT IN (
Просто в моем понимании `availability` это бинарная история: либо доступно, либо нет. Какие еще значения могут быть? Предлагаю вместо `INT` использовать `BIT` для атрибута `availability` и фильтровать по `availability = 1`

2024-07-21 12:50 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +	availability INT NOT NULL,
Давай сделаем типа `BIT`

2024-07-21 12:52 UTC, pklgn commented on SQL/SQL_HotelManagement.sql
> +	CONSTRAINT FK_Bookings_customer_id
В предыдущем комменте не отписал про все остальные ограничения, но их тоже именовать нужно не с большой буквы. То есть будет `FK_bookings_customer_id` и по аналогии во всех остальных ограничениях так же.

2024-07-21 16:48 UTC, sashass635 commented on SQL/SQL_HotelManagement.sql
> +WHERE  availability > 0 AND room_id NOT IN (
Поняла, я думала, что ```availability``` представляет собой количество доступных номеров. Например, есть 5 свободных номеров определенного типа.

2024-07-29 21:21 UTC, pklgn approved these changes
LGTM!

2024-08-06 22:11 UTC, merged