Fighters homework
sashass635/tl_practice_2024 pull request #6
Opened 2024-07-20 11:26 UTC by sashass635

В данном проекте было проведено пять тестов. Определение победителя в битве зависит от многих параметров, включая механизма случайного урона, который может варьироваться в диапазоне от -20% до +10%, поэтому в тестах определить конкретного победителя в битве становится сложно.

2024-07-20 21:22 UTC, pklgn commented on Fighters/Fighters.Tests/FighterTests.cs
За тесты нереальный респект!)

2024-07-20 21:27 UTC, pklgn commented on Fighters/Fighters.Tests/FighterTests.cs
> +            Assert.AreEqual( "Fighter 1", fighter.Name );
Я бы здесь и далее вынес в `expected` переменные тестируемые значения.
Например `expectedFighterName`
Но вообще если делать прям совсем красиво, то можно использовать библиотеку `FluentAssertions`
И получится код проверки вроде `fighter.Name.Should.Be("Fighter 1")`

2024-07-20 21:41 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +            int damageDone = startHealth - _currentHealth;
Интересная логика. По факту если дамага пришло больше, чем здоровья у персонажа, то значит ли это, что принято урона было меньше? Философский вопрос. Как вариант, можно было бы сделать `TakeDamage` с возвращаемым типом `void` и считать, что сколько дамага нанесли, столько боец и принял.

2024-07-20 21:42 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +
Лишними строками лучше не разделять ветки `case`.

2024-07-20 21:45 UTC, pklgn commented on Fighters/Fighters/Extensions/IFighterExtensions.cs
> +                Console.WriteLine( "Недостаточно бойцов для начала боя." );
Тут смешивается логика проверки и вывода сообщения. Лучше в коде извне основываться на результатах проверки `IsCorrect` и при необходимости выводить сообщение. Иначе метод находится на двух разных уровнях абстракции: с одной стороны он работает с бойцами, с другой -- выводит в консоль сообщение. Разные ответственности следует разделять по разным классам.

2024-07-20 21:45 UTC, pklgn commented on Fighters/Fighters/Extensions/IFighterExtensions.cs
> +    public static class IFighterExtensions
Почему тут появляется приставка `I`?

2024-07-20 21:52 UTC, pklgn commented on Fighters/Fighters/Extensions/IFighterExtensions.cs
> +        public static bool IsCorrect( this List<IFighter> fighters )
Название непонятное. Корректное для чего? Для начала боя? Но в другом контексте, вне боя, такая проверка лишена смысла. Лучше проверять там, где метод используется, то есть в контексте GameManager'а. Метод предлагаю переместить туда. Либо избавиться от него и поместить реализацию в место, где метод вызывается.

2024-07-20 21:53 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +                    case "fighters":
Может "list"? Потому что должно быть некоторое действие, команда. А тут существительное. `list` можно перевести как "перечислить".

2024-07-20 21:56 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +                    if ( !firstFighter.IsAlive() ) continue;
В одну строку лучше не писать, используй `{}`

2024-07-20 21:59 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +                    IFighter secondFighter = sortedFighters.FirstOrDefault( f => f != firstFighter && f.IsAlive() );
А не получится ли так, что второй боец почти всегда будет одним и тем же?

2024-07-20 22:00 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +                IFighter winner = sortedFighters.FirstOrDefault( f => f.IsAlive() );
Почему не взять просто из `fighters`?

2024-07-20 22:01 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +                    Console.WriteLine( $"Имя: {fighter.Name}" );
Лучше добавить разделитель между бойцами, либо выводить в одну строку всю инфу.

2024-07-20 22:05 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +        public string GetDamageInformation( IFighter fighter, int damageDone )
Лишний метод, на мой взгляд. Я могу вызывать метод в любой момент и получать сообщение, что боец такой-то нанес столько-то урона другому бойцу. Нарушение инварианта получается: не факт, что урон был нанесен.

2024-07-20 22:09 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/IFighter.cs
> +        string Name { get; }
Где-то есть `public`, где-то нет. По факту `public` в интерфейсах по умолчанию. Одно из правил чистого кода -- последовательность в принятии решений: если решили писать `public`, то пишем везде. Но, повторюсь, модификатор `public` в интерфейсах по умолчанию, поэтому можно и без него.

2024-07-20 22:09 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/IFighter.cs
> +        public string GetDamageInformation( IFighter fighter, int damageDone );
Выпилить.

2024-07-20 22:27 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +            string choice;
Переменная должна быть объявлена как можно ближе к месту, где она используется.

2024-07-20 22:28 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +                Console.WriteLine( "Все бойцы погибли. Ничья." );
А такое возможно?

2024-07-20 22:34 UTC, pklgn commented on Fighters/Fighters/Models/Armors/IronArmor.cs
> +
Где-то есть пустая строка в конце файла, где-то нет. В идеале привести к единому виду. Самый оптимальный вариант для этого: настроить [StyleCop](https://stackoverflow.com/questions/54729468/formatting-rule-to-have-blank-line-between-class-member-declarations). 
Но это необязательно для данной лабы, тут больше просто накидываю, какие инструменты бывают. Если интересно, можешь попробовать добавить.

2024-07-20 22:36 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +            bool criticalDamage = rnd.Next( 1, 101 ) < CriticalPercentChance;
`isCriticialDamage`

2024-07-20 22:37 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +            int originalDamage = _race.Damage + _fighterType.Damage + _weapon.Damage;
`original` по ходу выполнения метода теряется: одна и та же переменная обновляется. Я бы убрал упоминание того, что было какое-то исходное значение в переменной.

2024-07-20 22:39 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +            const double MinMultiplierDamage = 0.80;
константы на уровне метода не хранят. Метод принадлежит классу, значит класс и владеет константами. Нужно перенести их непосредственно в класс. Иначе это просто переменные, которые создаются каждый раз при вызове метода.

2024-07-20 22:47 UTC, pklgn commented on Fighters/Fighters/Models/FightersProfile/FightersProfile.cs
> +            List<IRace> race = new() { new Human(), new Orc() };
Может где-то единожды эти списки определять? По сути для каждого бойца набор характеристик на выбор один и тот же будет всегда. Стоит оптимизировать этот момент.

2024-07-20 22:48 UTC, pklgn commented on Fighters/Fighters/Models/FightersProfile/FightersProfile.cs
> +            List<IRace> race = new() { new Human(), new Orc() };
Предлагаю вынести в отдельный объект (нечто вроде конфигурации) все списки и переиспользовать эту конфигурацию при каждом вызове метода добавления бойца.

2024-07-20 22:50 UTC, pklgn commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +        private int CalculateInitiative() => _fighterType.Initiative + rnd.Next( 1, 16 );
Лучше сначала все `public` методы разместить, потом приватные.

2024-07-20 22:50 UTC, pklgn requested changes
Нужны доработки

2024-07-21 23:08 UTC, sashass635 commented on Fighters/Fighters/Models/Fighter/Fighter.cs
> +            int damageDone = startHealth - _currentHealth;
Реализовала метод ```TakeDamage``` с возвращаемым типом ```int```, поскольку нам же необходимо отслеживать урон, нанесенный бойцу во время раунда (по крайней мере, так указано в примере в ТЗ). Если же дамага пришло больше, чем здоровья у персонажа, то боец погибает.

2024-07-21 23:08 UTC, sashass635 commented on Fighters/Fighters/Extensions/IFighterExtensions.cs
> +    public static class IFighterExtensions
Убрала. Когда клонировала проект, чтобы доработать консольную игру, то изначально было ```IFighterExtensions``` .

2024-07-21 23:09 UTC, sashass635 commented on Fighters/Fighters/GameManager.cs
> +                    IFighter secondFighter = sortedFighters.FirstOrDefault( f => f != firstFighter && f.IsAlive() );
В данном случае, у нас же бойцы перед началом боя отсортированы по убыванию инициативы, то второй боец будет следующим по инициативе после первого, а потом они будут меняться каждый новый раунд из-за цикла ```for```, т.е. первый станет вторым, и наоборот.

2024-07-21 23:10 UTC, sashass635 commented
Доработала программу согласно замечаниям

2024-08-11 06:56 UTC, pklgn commented on Fighters/Fighters/Models/FightersProfile/SetOfCharacteristics.cs
> +    public class SetOfCharacteristics
Может назвать `FightersConfiguration`?

2024-08-11 07:08 UTC, pklgn commented on Fighters/Fighters/Models/FightersProfile/FightersProfile.cs
> +    public class FightersProfile
Что означает профиль в названии? Давай лучше назовем это `FighterFactory`. Так будет сразу понятно, какая ответственность у класса.

2024-08-11 07:12 UTC, pklgn commented on Fighters/Fighters/Models/FightersProfile/FightersProfile.cs
> +                Console.Write( v );
Что означает переменная `v` в названии? Нужно давать понятные и однозначные названия переменным. Использование подобных `v` идентификаторов это code smell. Почитать про них можно [тут](http://www.proglibs.appspot.com/CleanCode.html).

2024-08-11 07:13 UTC, pklgn commented on Fighters/Fighters/Models/FightersProfile/FightersProfile.cs
> +        public static int GetValidChoice( string v, int maxChoice )
Не очень понял, почему этот метод находится в классе, потому что он относится к правилам игры, а не к самому бойцу напрямую. Я бы вытащил метод в отдельный класс.

2024-08-11 07:16 UTC, pklgn commented on Fighters/Fighters/GameManager.cs
> +        public void AddFighter( IFighter fighter )
Точно ли должны быть модификаторы `public`? Насколько понимаю, в Program.cs только `Run` метод используется.

2024-08-11 07:18 UTC, pklgn requested changes
Нужно поправить небольшие замечания.

2024-08-11 12:10 UTC, sashass635 commented on Fighters/Fighters/GameManager.cs
> +        public void AddFighter( IFighter fighter )
Поменяла на ```private```, поскольку методы, кроме ```Run()```, используются только внутри ```GameManager```а

2024-08-29 17:53 UTC, merged